version: '1.0'
name: pipeline-20241220
displayName: pipeline-20241220
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-8c03bfa2
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: ut@nodejs
        name: unit_test_nodejs
        displayName: Nodejs 单元测试
        nodeVersion: 16.14.2
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - '# 在这里输入测试命令'
          - npm install && npm run test
        report:
          path: mochawesome-report
          file: mochawesome.json
          index: mochawesome.html
        checkpoints: []
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
