version: '1.0'
name: pipeline-20241220
displayName: giteeCICD
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-3ab23689
    displayName: CI
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: ut@nodejs
        name: unit_test_nodejs
        displayName: Nodejs 单元测试
        nodeVersion: 14.16.0
        commands:
          - npm install pnpm
          - '# 在这里输入测试命令'
          - pnpm install && pnpm run test
        report:
          path: mochawesome-report
          file: mochawesome.json
          index: mochawesome.html
        checkpoints: []
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 执行编译命令'
          - pnpm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
