version: '1.0'
name: pipeline-20241220
displayName: pipeline-20241220
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-94918b92
    displayName: CI
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 18.16.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - npm install pnpm
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.pnpm
        notify: []
        strategy:
          retry: '0'
  - name: stage-9d45cc84
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 18.16.0
        commands:
          - '# 执行编译命令'
          - pnpm install && pnpm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
  - name: stage-7849952f
    displayName: CD
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: CICDTest
          hostID:
            - f0f1a6ab-b28a-40cf-8cfc-030f0b7174fe
        deployArtifact:
          - source: build
            name: output
            target: /giteeCDtest
            dependArtifact: BUILD_ARTIFACT
        script:
          - cd /giteeCDtest
          - ls
          - tar -zxf output.tar.gz
          - echo 'Hello Gitee Go!'
        notify: []
        strategy:
          retry: '0'
